# **Business Understanding**

#### **Apple Global Product Sales Dataset**

11,500 synthetic sales transactions for iPhone, iPad, Mac, Apple Watch, AirPods, and Accessories across 47 countries, 514+ cities, sorted by Country → City → Date (2022 – 2024).

This dataset simulates a realistic global sales ledger for Apple Inc. products.It covers city-level transactions across multiple continents, currencies, sales channels,and customer demographics — ideal for retail analytics, market segmentation, price analysis, time-series forecasting, and geographic visualisation.

source: [Data set source](https://www.kaggle.com/datasets/ashyou09/apple-global-product-sales-dataset)

This dataset simulates a realistic global sales ledger for Apple Inc. products.It covers city-level transactions across multiple continents, currencies, sales channels,and customer demographics — ideal for retail analytics, market segmentation, price analysis, time-series forecasting, and geographic visualisation.

## **Data Understanding**

- head and tail (printing out the first 5 or few entries and the last entries)
- shape (dimensions)
- columns
- datatypes
- info
- describe numerical (descriptive)
- describe categroical

# Load Libraries

In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

### Load Data

In [6]:
apple_df = pd.read_csv("data/apple_global_sales_dataset.csv")

##Get  a Glimpse of the Data

In [9]:
apple_df.head(10)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,...,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,...,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,...,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,...,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,...,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept
5,APPL-00000006,2022-07-31,2022,Q3,July,Argentina,South America,Buenos Aires,Magic Keyboard,Accessories,...,ARS,907.0,280317.42,Apple Store,Cash,Education,55+,NaN,4.9,Kept
6,APPL-00000007,2022-08-01,2022,Q3,August,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,...,ARS,907.0,1762836.13,Apple Store,Gift Card,Government,35–44,NaN,3.6,Kept
7,APPL-00000008,2022-08-04,2022,Q3,August,Argentina,South America,Buenos Aires,iPhone 15 Pro Max,iPhone,...,ARS,907.0,7579762.72,Carrier Store,Gift Card,Education,25–34,iOS 16,4.7,Kept
8,APPL-00000009,2023-01-14,2023,Q1,January,Argentina,South America,Buenos Aires,Apple TV 4K (3rd Gen),Accessories,...,ARS,907.0,892415.44,Authorized Reseller,Gift Card,Government,18–24,NaN,4.7,Kept
9,APPL-00000010,2023-01-26,2023,Q1,January,Argentina,South America,Buenos Aires,iPad Mini (6th Gen),iPad,...,ARS,907.0,471685.35,Third-Party Retailer,Apple Pay,Business,25–34,NaN,3.6,Kept

In [8]:
apple_df.tail()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11495,APPL-00011496,2024-02-08,2024,Q1,February,Vietnam,Asia,Nha Trang,Apple Watch Series 9,Apple Watch,...,VND,24500.0,19575500.0,Third-Party Retailer,Gift Card,Individual,18–24,NaN,4.0,Kept
11496,APPL-00011497,2024-02-15,2024,Q1,February,Vietnam,Asia,Nha Trang,Mac Pro (M2 Ultra),Mac,...,VND,24500.0,166389790.0,Corporate / B2B,Gift Card,Education,45–54,NaN,4.9,Kept
11497,APPL-00011498,2024-08-28,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone 15,iPhone,...,VND,24500.0,86579325.0,Authorized Reseller,Debit Card,Government,35–44,iOS 16,3.8,Kept
11498,APPL-00011499,2024-08-31,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone SE (3rd Gen),iPhone,...,VND,24500.0,10755255.0,Apple Store,EMI / Installment,Education,55+,iOS 17,NaN,Kept
11499,APPL-00011500,2024-10-10,2024,Q4,October,Vietnam,Asia,Nha Trang,iPhone 15 Pro Max,iPhone,...,VND,24500.0,28972720.0,Online (Apple.com),EMI / Installment,Individual,35–44,Other,3.6,Kept

In [13]:
rows, columns = apple_df.shape
output = f"ROWS: {rows}  || COLUMNS {columns}"
print(output)

ROWS: 11500  || COLUMNS 27

In [14]:
apple_df.dtypes

sale_id                       str
sale_date                     str
year                        int64
quarter                       str
month                         str
country                       str
region                        str
city                          str
product_name                  str
category                      str
storage                       str
color                         str
unit_price_usd            float64
discount_pct                int64
units_sold                  int64
discounted_price_usd      float64
revenue_usd               float64
currency                      str
fx_rate_to_usd            float64
revenue_local_currency    float64
sales_channel                 str
payment_method                str
customer_segment              str
customer_age_group            str
previous_device_os            str
customer_rating           float64
return_status                 str
dtype: object

#Get Descriptive Stats of the Numerical Data

In [16]:
apple_df.describe()

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,1.150000e+04,8140.000000
mean,2022.997304,807.851191,3.841565,2.023478,777.365478,1568.319065,1029.406647,1.464369e+06,4.000934
std,0.821747,1112.437595,4.783161,1.443599,1072.915122,2839.759822,4072.334957,9.941160e+06,0.575192
min,2022.000000,26.690000,0.000000,1.000000,22.730000,23.000000,0.790000,2.130000e+01,3.000000
25%,2022.000000,180.147500,0.000000,1.000000,178.297500,305.740000,0.920000,1.041693e+03,3.500000
50%,2023.000000,593.905000,2.000000,1.000000,573.420000,833.040000,7.240000,6.164160e+03,4.000000
75%,2024.000000,958.387500,7.000000,3.000000,928.567500,1748.360000,91.500000,7.471653e+04,4.500000
max,2024.000000,7551.010000,15.000000,8.000000,7551.010000,59529.520000,24500.000000,5.075175e+08,5.000000

#### Descriptive stats
- MCTS -> Measures of central tendency (Mean, Median, Mode)
- MoV - > MEasures of variation (range, IQR, percentile, quartile, variance, standard deviation)

In [17]:
apple_df.describe(include='object')

/var/folders/0c/1j_h2q_d3cz5xx15_x7nbdyw0000gn/T/ipykernel_65355/1031726454.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  apple_df.describe(include='object')

,sale_id,sale_date,quarter,month,country,region,city,product_name,category,storage,color,currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,return_status
count,11500,11500,11500,11500,11500,11500,11500,11500,11500,6696,11500,11500,11500,11500,11500,11500,3444,11500
unique,11500,1096,4,12,47,8,514,43,6,10,20,38,6,7,4,5,6,3
top,APPL-00000001,2022-07-31,Q4,March,Japan,Europe,Singapore,Apple Watch SE (2nd Gen),iPhone,64 GB,Silver,EUR,Online (Apple.com),Credit Card,Government,25–34,Android,Kept
freq,1,23,2922,1047,274,3898,237,312,3444,944,1690,2433,1940,1683,2892,2347,595,10143

# Insights
-