# ** Business Understanding **

This dataset include data for the estimation of obesity levels in individuals from the countries of Mexico, Peru and Colombia, based on their eating habits and physical condition. The data contains 17 attributes and 2111 records, the records are labeled with the class variable NObesity (Obesity Level), that allows classification of the data using the values of Insufficient Weight, Normal Weight, Overweight Level I, Overweight Level II, Obesity Type I, Obesity Type II and Obesity Type III. 77% of the data was generated synthetically using the Weka tool and the SMOTE filter, 23% of the data was collected directly from users through a web platform.

[Data Source Link](https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition)

## ** Steps in conducting a hypothesis test: **
- Formulate the Null and Alternative Hypothesis
- Gather evidence(data)
- Calculate the test statistic
- Make a conclusion

## ** Import Necessary Libraries **

In [40]:
import numpy as np 
import pandas as pd
from scipy import stats
from sklearn.datasets import load_iris

## ** Load Dataset **

In [41]:
# If everything was loaded into 1 column, split it

if obesity_data_df.shape[1] == 1:
    obesity_data_df = obesity_data_df.iloc[:, 0].str.split(",", expand=True)

In [42]:
obesity_data_df.columns = [
    "Gender", "Age", "Height", "Weight",
    "family_history_with_overweight", "FAVC",
    "FCVC", "NCP", "CAEC", "SMOKE",
    "CH2O", "SCC", "FAF", "TUE",
    "CALC", "MTRANS", "NObeyesdad"
]

In [44]:
numeric_cols = ["Age", "Height", "Weight", "FCVC",
                "NCP", "CH2O", "FAF", "TUE"]

for col in numeric_cols:
    obesity_data_df[col] = pd.to_numeric(obesity_data_df[col], errors="coerce")

In [45]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = [
    "Gender", "family_history_with_overweight", "FAVC",
    "CAEC", "SMOKE", "SCC", "CALC", "MTRANS",
    "NObeyesdad"
]

encoder = LabelEncoder()

for col in categorical_cols:
    obesity_data_df[col] = encoder.fit_transform(obesity_data_df[col])

In [47]:
obesity_data_df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,0,0,2.0,3.0,0,0,2.0,0,0.0,1.0,0,0,0
1,0,21.0,1.52,56.0,0,0,3.0,3.0,0,0,3.0,0,3.0,0.0,0,0,0
2,0,23.0,1.80,77.0,0,0,2.0,3.0,0,0,2.0,0,2.0,1.0,0,0,0
3,0,27.0,1.80,87.0,0,0,3.0,3.0,0,0,2.0,0,2.0,0.0,0,0,0
4,0,22.0,1.78,89.8,0,0,2.0,1.0,0,0,2.0,0,0.0,0.0,0,0,0

In [48]:
obesity_data_df['NObeyesdad'].describe()

count    2111.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: NObeyesdad, dtype: float64

In [11]:

obesity_data_df.columns = [
    "Gender", "Age", "Height", "Weight",
    "family_history_with_overweight", "FAVC",
    "FCVC", "NCP", "CAEC", "SMOKE",
    "CH2O", "SCC", "FAF", "TUE", 
    "CALC", "MTRANS", "NObeyesdad"
]

In [22]:
obesity_data_df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64,yes,no,2,3,Sometimes,no,2,no,0,1,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56,yes,no,3,3,Sometimes,yes,3,yes,3,0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.8,77,yes,no,2,3,Sometimes,no,2,no,2,1,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.8,87,no,no,3,3,Sometimes,no,2,no,2,0,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.8,no,no,2,1,Sometimes,no,2,no,0,0,Sometimes,Public_Transportation,Overweight_Level_II

In [39]:
# Convert only numeric-like columns
for col in obesity_data_df.columns:
    try:
        obesity_data_df[col] = pd.to_numeric(obesity_data_df[col], errors="coerce")
    except:
        pass

# Preview
obesity_data_df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,NaN,21.0,1.62,64.0,NaN,NaN,2.0,3.0,NaN,NaN,2.0,NaN,0.0,1.0,NaN,NaN,NaN
1,NaN,21.0,1.52,56.0,NaN,NaN,3.0,3.0,NaN,NaN,3.0,NaN,3.0,0.0,NaN,NaN,NaN
2,NaN,23.0,1.80,77.0,NaN,NaN,2.0,3.0,NaN,NaN,2.0,NaN,2.0,1.0,NaN,NaN,NaN
3,NaN,27.0,1.80,87.0,NaN,NaN,3.0,3.0,NaN,NaN,2.0,NaN,2.0,0.0,NaN,NaN,NaN
4,NaN,22.0,1.78,89.8,NaN,NaN,2.0,1.0,NaN,NaN,2.0,NaN,0.0,0.0,NaN,NaN,NaN

In [28]:
numeric_cols = ["Age", "Height", "Weight", "FCVC", "NCP", "CH2O", "FAF", "TUE"]

for col in numeric_cols:
    obesity_data_df[col] = pd.to_numeric(obesity_data_df[col], errors="coerce")

In [31]:
obesity_data_df.dtypes

Gender                            float64
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight    float64
FAVC                              float64
FCVC                              float64
NCP                               float64
CAEC                              float64
SMOKE                             float64
CH2O                              float64
SCC                               float64
FAF                               float64
TUE                               float64
CALC                              float64
MTRANS                            float64
NObeyesdad                        float64
dtype: object

In [32]:
type(obesity_data_df)

pandas.DataFrame

In [33]:
obesity_data_df.keys()

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='str')

In [34]:
obesity_data_df.describe()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
count,0.0,2111.000000,2111.000000,2111.000000,0.0,0.0,2111.000000,2111.000000,0.0,0.0,2111.000000,0.0,2111.000000,2111.000000,0.0,0.0,0.0
mean,NaN,24.312600,1.701677,86.586058,NaN,NaN,2.419043,2.685628,NaN,NaN,2.008011,NaN,1.010298,0.657866,NaN,NaN,NaN
std,NaN,6.345968,0.093305,26.191172,NaN,NaN,0.533927,0.778039,NaN,NaN,0.612953,NaN,0.850592,0.608927,NaN,NaN,NaN
min,NaN,14.000000,1.450000,39.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,1.000000,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,NaN,19.947192,1.630000,65.473343,NaN,NaN,2.000000,2.658738,NaN,NaN,1.584812,NaN,0.124505,0.000000,NaN,NaN,NaN
50%,NaN,22.777890,1.700499,83.000000,NaN,NaN,2.385502,3.000000,NaN,NaN,2.000000,NaN,1.000000,0.625350,NaN,NaN,NaN
75%,NaN,26.000000,1.768464,107.430682,NaN,NaN,3.000000,3.000000,NaN,NaN,2.477420,NaN,1.666678,1.000000,NaN,NaN,NaN
max,NaN,61.000000,1.980000,173.000000,NaN,NaN,3.000000,4.000000,NaN,NaN,3.000000,NaN,3.000000,2.000000,NaN,NaN,NaN

In [35]:
obesity_data_df['NObeyesdad'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: NObeyesdad, dtype: float64